[package]
name = "self-replace"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.5.0"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.48.0", features = [
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
] }
