name: Tests

on: [push, pull_request]

jobs:
  test-latest:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check
        run: make check
      - name: Demo
        run: ./demo.sh

  test-latest:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check
        run: make check
      - name: Demo
        run: demo.bat

  test-stable:
    name: Build on 1.61.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.61.0
      - name: Check
        run: make check
